name: Check

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

concurrency:
  group: ci-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 10.14.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm exec eslint .
      - name: Typecheck
        run: pnpm run typecheck
